### ISSUE TITLE
Confirm use of static peers, protocols and usage quota

### ISSUE THREAD

**Issue by felicio** [status-im/community-dapp#23]
## What

- Confirm use of either `wakuv2` or `status` static peers for reliability
- Confirm use of either Light Push or Relay for storing
- Confirm Waku usage quota

## Why

- https://github.com/status-im/status-desktop/issues/7534#issuecomment-1330515894

## When

- https://github.com/status-im/status-desktop/milestone/56

**Comment by felicio** [comment]
@jm-clius this project is to allow users to vote on communities, and retrieve other users' votes, which should be eventually listed in Status' directory. Among other things it depends on Waku as well.

Please,

1. For now, would you suggest using static peers from `wakuv2` or `status` static peers for reliability?
2. If `status`, could we redeploy Light Push on prod or would you still recommend using Relay?
3. Can you think of a guaranteed quota for such use case (e.g. 100 pushes/min., 10 queries/min.)?

Cc @prichodko @jkbktl

**Comment by prichodko** [comment]
It also retrieves community descriptions for listed communities.

**Comment by fryorcraken** [comment]
1. Should be Status fleet, you should use the same dns discovery enr tree than Status desktop. I would suggest to check with Status team on whether websocket are enabled on Status fleet.
2. We recommend using light clients protocol for Web. You can use filter v1 for one for now but we would also recommend considering dogfooding filter v2 (we are close to delivering it in js-waku and nwaku
3. This kind of information is what we can learn as part of a dogfooding phase.

**Comment by felicio** [comment]
@fryorcraken 

> you should use the same dns discovery

Why would you suggest to use discovery over static addr here?

> We recommend using light clients protocol 

I'm asking, and about Light Push specifically too, because it was once considered stable however later rolled-back on prod. Could you confirm it's stable again?

> it causes instability in what is assumed to be stable protocols. This is not a protocol rework, just avoiding unnecessary crashes. – https://discord.com/channels/864066763682218004/978113702471561278/1047095369563115540

**Comment by fryorcraken** [comment]
> > you should use the same dns discovery
> 
> Why would you suggest to use discovery over static addr here?

Nodes to be used by Web client may change: 
- As number of users or load increases
- As sharding gets deployed
- As other events happen, such as instability related to websocket (or filter)

When using static addr, a change on what bootstrap node to be used will have to be reflected in code (e.g. release new version, get users to refresh page, etc).

By using dns discovery, you can decoupled infra change and code change: changing bootstrap node would need to only update a DNS TXT record, without changing code.

I think it might be safer to use a different DNS name for Status Web. Especially in light of WS memory above, you may want to somehow dedicate some nodes to the web without impacting desktop nodes. Or at least, have the option to do so. WDYT @jm-clius?

> > We recommend using light clients protocol
> 
> I'm asking, and about Light Push specifically too, because it was once considered stable however later rolled-back on prod. Could you confirm it's stable again?
> 
> > it causes instability in what is assumed to be stable protocols. This is not a protocol rework, just avoiding unnecessary crashes. – [discord.com/channels/864066763682218004/978113702471561278/1047095369563115540](https://discord.com/channels/864066763682218004/978113702471561278/1047095369563115540)

Apologies, I had forgotten the context. I believe some of the initial issue were sorted but ultimately, the Filter v2 brings the refactoring necessary for stability. @jm-clius to confirm please.

**Comment by jm-clius** [comment]
If at all possible, I wouldn't use filter v1 because of its unreliability. In my mind, filter v2 may already be a better option (although dogfooding would be required), but might require some changes in the client which is unacceptable given the time frame.

However, from my understanding above, the protocols you want to use are:
`lightpush` and `store` (not `filter`)? cc @felicio 

Afaik we never picked up an issue with lightpush specifically, although it's also mostly un-dogfooded and we'd have to monitor for any unexpected issues. We could enable `lightpush` for this purpose on the `status.prod` fleet although I'd suggest testing the feature on the `status.test` fleet first. It was disabled because it is most often used in combination with `filter`, but can operate separately.

**Comment by jm-clius** [comment]
Another question, is the idea that this app simply publishes to the `store` or that the published messages be relayed to everyone in the community live? If these messages have no need to be relayed live to everyone in the community, it seems to me it should not be published on the community pubsub topic, but on a separate pubsub topic (which must be configured on the store nodes) from where it can also be retrieved on demand.

**Comment by felicio** [comment]
@jm-clius 

> However, from my understanding above, the protocols you want to use are:
lightpush and store (not filter)?

Correct.

This dapp is an inherited project which is due this Friday. But for future releases, I can think of a use case where Filter could be used to make the voting stats real-time (see screenshot).

> We could enable lightpush for this purpose

Perfect.

If we agree here to go this route, could I please ask you to do so or should I reach out to Jakub?

> is the idea that this app simply publishes to the store

Right.

For now, messages carrying the votes would be published when user votes and requested the community preview loads thus not real-time (see screenshot)

> no need to be relayed live to everyone in the community

True.

The messages are technically unrelated to those that might be sent within a community. It's a separate app on the network.

> dedicate some nodes to the web without impacting desktop nodes

> a separate pubsub topic (which must be configured on the store nodes) from where it can also be retrieved on demand.

I understand, but personally don't expect the traffic to "make a dent" and I'm inclined doing so later on should a related issue arise.

Do you agree? I'll side with you on this one, if you say it'd be better anyway and is easy to set up.

<img width="753" alt="image" src="https://user-images.githubusercontent.com/13265126/235858072-587737d7-a93f-42af-9064-056301f6837b.png">

**Comment by jm-clius** [comment]
Thanks for your answers, @felicio! As discussed elsewhere my suggestion is the following:
1. Enable `lightpush` only on one `status.prod` node for now (let's say `node-01.ac-cn-hongkong-c.status.prod`). This is simply a config change, so the image itself (i.e. nwaku version) should not be redeployed or upgraded.
2. Use only that node for the feature for now. I'm assuming this lack of redundancy will be OK as one node may be offline for brief periods of times, but it should be good enough to roll out the feature.

For (1), could you contact Jakub? Happy to help clarify requirements here and verify that the config change worked as expected.

**Comment by felicio** [comment]
> Thanks for your answers, @felicio! As discussed elsewhere my suggestion is the following:
> 
> 1. Enable `lightpush` only on one `status.prod` node for now (let's say `node-01.ac-cn-hongkong-c.status.prod`). This is simply a config change, so the image itself (i.e. nwaku version) should not be redeployed or upgraded.
> 2. Use only that node for the feature for now. I'm assuming this lack of redundancy will be OK as one node may be offline for brief periods of times, but it should be good enough to roll out the feature.
> 
> For (1), could you contact Jakub? Happy to help clarify requirements here and verify that the config change worked as expected.

@jakubgs please, could you re-enable `lightpush` protocol on `node-01.ac-cn-hongkong-c.status.prod`? Would you like me to create a new issue?

I think it was disabled at https://github.com/status-im/infra-status/commit/f52ec7e1d923b332aba232e6b2e40b877ee353e2.

**Comment by jakubgs** [comment]
Done:

- https://github.com/status-im/infra-status/commit/cd2c7b51 - status.prod: enable lightpush on ac-cn-hongkong-c

```
admin@node-01.ac-cn-hongkong-c.status.prod:~ % grep lightpush /docker/nim-waku/docker-compose.yml
      --lightpush=true
```

**Comment by felicio** [comment]
My notes:

Monitoring

- https://grafana.infra.status.im/goto/CNs2nEs4k?orgId=1
- https://grafana.infra.status.im/goto/w6_T7Es4z?orgId=1
