### ISSUE TITLE
Contract deployment

### ISSUE THREAD

**Issue by osmaczko** [status-im/community-dapp#28]
Implement shorter voting periods and reduced intervals between votes for the first release. This approach will allow us to facilitate a smoother testing process.

https://github.com/status-im/community-dapp/blob/20d0d82a465e123463e6155b8109a9328df0d665/packages/contracts/deploy/deploy.ts#L108-L115

Acceptance criteria:
- [x] define configuration for first release
- [x] update https://github.com/status-im/community-dapp/blob/master/packages/DApp/src/components/Rules.tsx (#30)
- [x] update https://github.com/status-im/community-dapp/blob/master/packages/DApp/src/components/card/RemoveAmountPicker.tsx (#32)
- [x] #46
- [x] #47
- [x] https://github.com/status-im/community-dapp/issues/84

**Comment by osmaczko** [comment]
```
votingLength = 2 days
votingVerificationLength = 1 day
timeBetweenVoting = 2 days
featuredVotingLength = 2 days
featuredVotingVerificationLength = 1 day
cooldownPeriod = 2
featuredPerVotingCount = 3
```

**Comment by felicio** [comment]
@osmaczko

1. Do you mind if we kept this open until deployed and later reverted again? For tracking.
2. When are you going to deploy it?
3. And when you do, could leave comments here about how you did so and what you're doing for monitoring?

**Comment by felicio** [comment]
My notes:

- 30d waku retention
