### ISSUE TITLE
Fetch community info from waku network

### ISSUE THREAD

**Issue by osmaczko** [status-im/community-dapp#3]
Right now, communities data is [mocked](https://github.com/status-im/community-dapp/blob/master/packages/DApp/src/helpers/apiMockData.ts). Community info/details fetching from waku network needs to be implemented.

Acceptance criteria:

- [ ] Community info/details are fetched from waku network.
- [ ] Would be great if we could still reach mocked data through some flag for development purposes (c/o @osmaczko)

**Comment by felicio** [comment]
Discussion: https://discord.com/channels/@me/1096817477599625296/1097441304151081081

**Comment by felicio** [comment]
Fetching example: https://github.com/status-im/status-web/blob/843477175311865ab69187e00cf4e2054af6069a/packages/status-js/src/request-client/request-client.ts#L86-L97
