### ISSUE TITLE
Make sure the same key format is provided to contracts

### ISSUE THREAD

**Issue by osmaczko** [status-im/community-dapp#43]
Contracts are not designed to recognize differing public key formats, hence, supplying the public key in two separate formats can be interpreted by the contract as two distinct entities. This could create inconsistencies, such as when users input the same public key in both its uncompressed and compressed forms.

Acceptance Criteria:
- users should retain the ability to input either the uncompressed or compressed form of the public key
- only the uncompressed form of the public key should be transmitted to contract endpoints

**Comment by osmaczko** [comment]
> @osmaczko why uncompressed? Can't we leave the compressed format since it's what the client app is sending.

There is no rationale behind that decision other than the desire for consistency. Using 'compressed' is also acceptable. :+1:

**Comment by felicio** [comment]
@osmaczko closing then
