### ISSUE TITLE
_evaluateVotes would run out of gas if there are too many voters

### ISSUE THREAD

**Issue by 3esmit** [status-im/community-dapp#65]
https://github.com/status-im/community-dapp/blob/7836a7692981b6796fa9c9bf0ae0d5f8cce14496/packages/contracts/contracts/VotingContract.sol#L230

This assumes the blockchain have infinite processing capabilities for the tabulation loop, and splitting the processing in multiple transactions opens to double voting because the balances are not locked. This works fine for small rooms (with just a few voters), but when there are hundreds of voters, not just it would get extremely expansive for a single actor, it eventually would surpass the block gas limit, making the tabulation impossible.

**Comment by osmaczko** [comment]
Thank you @3esmit for pinpointing the issue. As we discussed in today's meeting, the proposed solution is to make SNT a MiniMeToken. This will allow us to verify votes across multiple transactions using `balanceOfAt(endOfVoting)`.

Note:
_This will require some minor modifications to our existing contracts and user interface, considering that we now have to account for the potential scenario where the finalization stage may be executed in multiple steps/transactions._

**Comment by John-44** [comment]
If any design work is needed for UI changes, @benjthayer is the person to ping.
