### ISSUE TITLE
Deploy contracts on Optimism

### ISSUE THREAD

**Issue by 0x-r4bbit** [status-im/community-dapp#84]
Once #83 and testing is done, we need to deploy the contracts on optimism.

To do that, the following command needs to be executed from within `packages/contracts`:

```
$ MNEMONIC=$MNEMONIC forge script script/DeployContracts.s.sol --rpc-url $RPC_URL --broadcast
```

Where

- `$MNEMONIC` is the mnemonic that has the deployment account. The deployment script will use the first account (`index 0`) by default
- `$RPC_URL` is the RPC endpoint for the network
- `--broadcast` needs to be used to actually send the transactions, otherwise the deployment is only simulated

**Comment by osmaczko** [comment]
Blocked by SNT deployment on Optimism

**Comment by 0x-r4bbit** [comment]
Deployment of contracts to OP Mainnet has happened.
Failed to verify contracts though. But I think this issue can eb closed.
